export const GET_AUDIO_LIST_LOADING = 'GET_AUDIO_LIST_LOADING';
export const GET_AUDIO_LIST_SUCCESS = 'GET_AUDIO_LIST_SUCCESS';
export const GET_AUDIO_LIST_FAIL = 'GET_AUDIO_LIST_FAIL';
export const SEND_AUDIO_LIST_LOADING = 'SEND_AUDIO_LIST_LOADING';
export const SEND_AUDIO_LIST_SUCCESS = 'SEND_AUDIO_LIST_SUCCESS';
export const SEND_AUDIO_LIST_FAIL = 'SEND_AUDIO_LIST_FAIL';
